/**
 * 2>Even Fibonacci numbers
 * 
 * 	Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * 	By starting with 1 and 2, the first 10 terms will be:
		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 	find the sum of the even-valued terms.
 * 
 * out put:4613732
 * @author kishoremajji
 *
 */


public class Q2 {
	public static void getEvenFibonaci(long n) {
		long sum = 0;
		int a = 0;
		int b = 1;
		int c = a + b;
		while (c < n) {

			if (c % 2 == 0) {

				sum = sum + c;

			}
			c = a + b;
			a = b;
			b = c;
		}
		System.out.println(sum + "  sum ");
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		getEvenFibonaci(4000000);
	}

}
